build: kill test app immediately instead of waiting
The more tests we have, the more likely it is that we'll see at least
one unhandled rejection timeout error from deep in playwright resulting
from calling ElectronApplication.close() and looking something like:

  TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (server/progress.js:75:30)
    at ElectronApplication._waitForEvent (server/electron/electron.js:99:35)
    at ElectronApplication.close (server/electron/electron.js:90:29)
    at ElectronApplicationDispatcher.close (dispatchers/electronDispatcher.js:59:28)
    at DispatcherConnection.dispatch (dispatchers/dispatcher.js:178:52)

This change bypasses the close function altogether, instead killing the
app and closing the node process connection manually.